### ISSUE TITLE
Missing upgrade cost calculations for certain MKs

### ISSUE THREAD

**Issue by zhuyifei1999** [blackeyefly/blackeyefly.github.io#1]
I've been using this tool for some tower cost calculations (often for CTs), and I've been noticing that the [code for cost calculation](https://github.com/blackeyefly/blackeyefly.github.io/blob/main/src/models/utils.ts#L226) doesn't account for many MKs. These are the ones I see (might miss some idk):

* Cheap 'Rangs: 000 boomer -$50
* Budget Clusters: 003 bomb -$100
* Come On Everybody: (complicated)
* Cheaper Maiming: 400 sniper -$1000
* Budget Artillery: 040 mortar -$600
* Cheaper Doubles: 300 ninja -$100
* Warm Oak: 020 druid -$100
* First Last Line of Defense: first 000 spike -$150
* Hi-value Mines: 400 spike -$1500

I noticed this while looking up the cost of middle-path druids and they don't match what I saw in game, then I found that they are affected by MK. Not sure how you want to fix this so I didn't send a PR.

**Comment by blackeyefly** [comment]
Thanks for the suggestion, this is one of many features I've been too lazy to implement yet. I'll try to work on it, now that I know people are actually using my website.

**Comment by JavaTryCatchMe** [comment]
Also [Aeronautic Subsidy](https://bloons.fandom.com/wiki/Aeronautic_Subsidy)
